### ISSUE TITLE
Get path returns false when not found and when the actual value is false

### ISSUE THREAD

**Issue by banstola** [Skyscanner/JsonPath-PHP#11]
Consider the following case:

```{"isAvailable":false}```

If I want to check is is `isAvailable` is exists then I do `$object->get("$.isAvailable")` which will return false but this also implies that this field does not exist. Or is there a way to check certain  path exists or not?

**Comment by Galbar** [comment]
Hi @banstola,
This behaviour is defined in the specification of JSONPath [0]. The function would return an array with the results or false. This is also the default behaviour in this library:
```php
$jsonObject = new JsonObject('{ "isAvailable": false }');

$r = $jsonObject->get("$.isAvailable");
var_dump($r);
// Output:
// array(1) {
//   [0] =>
//   bool(false)
// }

$r = $jsonObject->get("$.notThere");
var_dump($r);
// Output:
// bool(false)
```
As you can see, when the value is there it returns an array with it, and if it is not, it returns `false`.

From your description I imagine you are using the _SmartGet_ feature [1]. With this feature enabled, there is no way to know whether `false` is the value the path points to or there is no value pointed to by the path.

[0] http://goessner.net/articles/JsonPath/index.html#e4
[1] https://github.com/Skyscanner/JsonPath-PHP#smartget

**Comment by banstola** [comment]
Hi,
Thank you for clearing it up. I was using smartGet .
