### ISSUE TITLE
Instantiating JsonObject using a smartGet parameter changes empty json object string to empty array string

### ISSUE THREAD

**Issue by Anand-Moghe** [Skyscanner/JsonPath-PHP#15]
I am having a peculier issue while using  JsonObject like below:

```$myJsonPathObject = new JsonObject( $myJsonString, true);```

OR

```$myJsonPathObject = new JsonObject( $myJsonString);```

If your $myJsonString has empty JSON string like ` "Rules" : {}  `, then the empty object notation  is getting converted to empty array [ ]  
E.g.

` "Rules" : {}  ` becomes ` "Rules": []  `

**How do I fix this because we want to preserve the empty json object notation.**

**Comment by Anand-Moghe** [comment]
I think this is expected behaviour. So closing the issue.

**Comment by Galbar** [comment]
Hi! Yes! this is because of how PHP decodes json into an array.

**Comment by Anand-Moghe** [comment]
It could have been nicer if JsonObject somehow provided additional options for users to preserve the empty object by not using array ( `json_decode( $json_Strin_passed_by_user, true) `) but instead use the stdClass internally (like by using `json_decode( $json_Strin_passed_by_user, false)` ). The issue I was referring to is there because the constructor always forces array conversion instead of converting to the stdClass. The only difference between array and stdClass is the `[]` notation vs `->` for accessing the json value using key. And using stdClass will preserve the empty object notation.
