### ISSUE TITLE
Can't run test

### ISSUE THREAD

**Issue by mranon0007** [Skyscanner/JsonPath-PHP#16]
I belive this is not an issue but I can't figure out how to run the tests.
I installed library using Composer.
Then I ran the following command in terminal:

php \vendor\skyscanner\jsonpathapp\test.php "$..*[?(@.category == 'fiction' and @.price < 10 or @.color == \"red\")].price"

and I get an error "Can't find Autoload.php". Can you please tell me how to run the test case?

**Comment by Galbar** [comment]
Hi! I had never tried to run the `test.php` from an installed package.

It works if you change the line 18 to `include __DIR__ . '/../../../autoload.php';` in `test.php`.

You can also just clone the repo and it should work out of the box.

Feel free open a PR with a fix.
