### ISSUE TITLE
Creating node using set method 

### ISSUE THREAD

**Issue by banstola** [Skyscanner/JsonPath-PHP#17]
This is not an issue rather asking for help or suggestion . 

I have a situation where I need to create nodes dynamically and it has worked far.

I have two cases 
If i want to created an array like `['contacts'=>['firstName'=>'first name']]`
then i can do 

$jsonPathObject = new JsonObject([]) ;
$res = $jsonPathObject->set('$.contacts.firstName', 'first name')->getValue();

$res is   `['contacts'=>['firstName']]` 

but 

 `$res = $jsonPathObject->set('$.contacts[*].firstName', 'first name')->getValue();`
would result in 

`['contacts'=>[] ]`

Is there any possibility for it to create an array and create array of  array instead of an empty array because my need would be to have array

 `$res = ['contacts'=> [ ['firstName'=>'foo']]`  when I set   
`$jsonPathObject->set('$.contacts[*].firstName', 'first name')->getValue();`

**Comment by Galbar** [comment]
Hi!
To get that result you can do `$jsonPathObject->set('$.contacts[0].firstName', 'first name')->getValue();`

Cheers

**Comment by banstola** [comment]
This works but if in a scenario like below where you have to create an array of arrays  it does not work.

Say I have a data like [[ 'name'=> 'foo' ], ['name'=>'bar']] then I want to create new array using jsonpath set 
E.g. 
```
[
$contacts = [

['firstName'=>'foo','age'=>23],
['firstName'=>'bar' , 'age'=>26]
]
]
```

With my current implementation it always overrides instead of appending to new array to the existing array which I am setting. 


I check if an array exists or not if not i create the array that should hold the arrays then I want to add more member to this array

**Comment by Galbar** [comment]
Maybe what you are looking for is `JsonObject::add()`?
```
    /**
     * Append a new value to all json objects/arrays that match
     * the $jsonPath path. If $field is not null, the new value
     * will be added with $field as key (this will transform
     * json arrays into objects). This method returns $this to
     * enable fluent interface.
     *
     * @param string $jsonPath jsonPath
     * @param mixed $value value
     * @param string $field field
     *
     * @return JsonObject
     */
    public function add($jsonPath, $value, $field=null) {...}
```

**Comment by banstola** [comment]
I will try with this. Maybe it does not fit the situation that I am looking for. I am trying to create mapping between two json data so that I could transform one json data to another . I have made a work around for now. Thank you for your help so far.
