### ISSUE TITLE
Receiving error while retrieving value for numeric property name

### ISSUE THREAD

**Issue by Anand-Moghe** [Skyscanner/JsonPath-PHP#18]
I have a JSON which has numeric property key.
E.g.
```
{
   ......
  "9845656" : "0",
}
```

When I am trying to get the value of the property using JSON path, I am getting exception 
Error in JSONPath near '.9845656' 

Following is the sample code that throws this error. 
 `$jsonObject->get("$.{$jsonPathLocation}.{$key}");`

**How am I supposed to construct the JSON Path so that I can read the value of a numeric property name?**

**Comment by Anand-Moghe** [comment]
I have found a workaround by using the array syntax:
`$jsonObject->get("$.{$jsonPathLocation}[$indexOfKey_In_Parent_node]");`

**Comment by Galbar** [comment]
Hi! That is the intended way of dealing with this
