### ISSUE TITLE
The requested package skyscanner/jsonpath 0.8.0.0 could not be found

### ISSUE THREAD

**Issue by cesaregerbino** [Skyscanner/JsonPath-PHP#6]
I'm trying to follow the installation instructions, so I've added this ...

```
"require": {
    "skyscanner/jsonpath": "dev-master"
}
```

in my composer.json and then I've tried

`composer update`

but my system (Ubuntu 15.10), says ... 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package skyscanner/jsonpath 0.8.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
I can't find that file in the repo .... Suggestions?

Cesare

**Comment by Galbar** [comment]
I can't reproduce in my Ubuntu installation. What I did:
```
mkdir test
cd test
echo '{"require":{"skyscanner/jsonpath":"dev-master"}}' > composer.json
composer update
```
I got the output:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing skyscanner/jsonpath (dev-master 71c4ce3): Cloning 71c4ce39f8 from cache
Writing lock file
Generating autoload files
```

Did you check https://getcomposer.org/doc/articles/troubleshooting.md#package-not-found ?

**Comment by Galbar** [comment]
Did you manage to get it installed?

**Comment by cesaregerbino** [comment]
Hi Galbar .... following your suggestion I've installed (I think .... ), anyway I've the code now.

I'm quite a newbie in PHP so sorry for the trivial question .... I've tried to build a little example but it doesn't work .... Here you're how I'm organizing my code 

![image](https://user-images.githubusercontent.com/4707083/29983605-ff55ec80-8f56-11e7-874b-e7fba9bca2bc.png)

and here you're my code for test ... 

```
<?php
    ini_set('display_errors', 'On');
    error_reporting(E_ALL);

    use JsonPath\JsonObject

    $theJson = '{
      	"codiciColore": [{
      		"id": 2,
      		"descrizione": "Giallo",
      		"rgb": "FFFF00",
      		"priorita": 2,
      		"situazionePazienti": {
      			"numeroPazienti": 9,
      			"numeroPazientiInVisita": 9,
      			"mediaAttesa": "00:22",
      			"numeroPazientiInAttesa": 0
      		}
      	}, {
      		"id": 3,
      		"descrizione": "Verde",
      		"rgb": "00FF00",
      		"priorita": 3,
      		"situazionePazienti": {
      			"numeroPazienti": 16,
      			"numeroPazientiInVisita": 9,
      			"mediaAttesa": "03:03",
      			"numeroPazientiInAttesa": 7
      		}
      	}]
   }';

   $jsonObject = new JsonObject();

?>
```
When I try to execute it using `php testSkyScanner.php` I obtain this error ...

`PHP Fatal error:  Class 'JsonPath\JsonObject' not found in /var/www/html/Test/tmp/MyTestSkyScanner/testSkyScanner.php on line 33`

Any suggestion will be appreciated ... thank you in advance!

Cesare

**Comment by cesaregerbino** [comment]
There is ad error in my code ... 

`use JsonPath\JsonObject`

probably must be

`use JsonPath/JsonObject`

In thy way the error is

```
PHP Warning:  The use statement with non-compound name 'JsonPath' has no effect in /var/www/html//Test/tmp/MyTestSkyScanner/testSkyScanner.php on line 7
PHP Parse error:  syntax error, unexpected '/', expecting ',' or ';' in /var/www/html/Test/tmp/MyTestSkyScanner/testSkyScanner.php on line 7
```

**Comment by Galbar** [comment]
Hi! There is one supported and recommended way to install the library: using [composer](https://getcomposer.org/).

`composer`  will create a `vendor/` folder with all the dependencies installed with it. Inside the `vendor` folder there will also be a `autoload.php` file.

Now imagine we have the following file distribution:
```
.
├── app.php
└── composer.json
```
`composer.json` contains the following:
```javascript
{
    "require": {
        "php": ">=5.4",
        "skyscanner/jsonpath": "dev-master"
    }
}
```
If we run `composer install` in this directory it will create the `vendor/` directory.
Now lets look at `app.php`'s contents:
```php
<?php
include "vendor/autoload.php";

use JsonPath\JsonObject;

$jsonObject = new JsonObject();
$jsonObject->{"$.hello"} = "world";
echo $jsonObject;
```
If we now run `php app.php` we get the output `{"hello":"world"}`.

Notice that I included the `autoload.php` file before the `use ...` line. That file is what allows the usage of `use` to import modules and classes.

I hope this helps!

**Comment by cesaregerbino** [comment]
Thanks! I'll try to follow your example ad adapt it at my code!!

**Comment by cesaregerbino** [comment]
I've tried and now I can replicate your very clear example but I've still some problems .... .

I've tried to execute yout `test.php` and all works fine but if I try to use this code (that is quite similar ....)

```
<?php
    ini_set('display_errors', 'On');
    error_reporting(E_ALL);

    include "vendor/autoload.php";

   $theJson =
   '{ "store": {
        "book": [
          { "category": "reference",
            "author": "Nigel Rees",
            "title": "Sayings of the Century",
            "price": 8.95,
            "available": true
          },
          { "category": "fiction",
            "author": "Evelyn Waugh",
            "title": "Sword of Honour",
            "price": 12.99,
            "available": false
          },
          { "category": "fiction",
            "author": "Herman Melville",
            "title": "Moby Dick",
            "isbn": "0-553-21311-3",
            "price": 8.99,
            "available": true
          },
          { "category": "fiction",
            "author": "J. R. R. Tolkien",
            "title": "The Lord of the Rings",
            "isbn": "0-395-19395-8",
            "price": 22.99,
            "available": false
          }
        ],
        "bicycle": {
          "color": "red",
          "price": 19.95,
          "available": true
        }
      },
      "authors": [
        "Nigel Rees",
        "Evelyn Waugh",
        "Herman Melville",
        "J. R. R. Tolkien"
      ]
    }';

   $jsonObject = new JsonPath\JsonObject();

   $jsonPathExpr = "$..*[?(@.category == 'fiction' and @.price < 10 or @.color == \"red\")].price";

   $r = $jsonObject->get($jsonPathExpr);

   print json_encode($r)

?>

```
from command line `php testSkyScanner.php` the result is `false`. 

How may I specify the json path expression in my code?

Thanks!!!

**Comment by cesaregerbino** [comment]
I've tried to follow your clear instructions and now all work fine!

Thanks!
